# Site settings
title: Pacific Crest Trail
header-img: img/home-bg.jpg
email: your-email@yourdomain.com
copyright_name: Adventures Not Vacations
description: "My trail journal while I hike the Pacific Crest Trail, northbound, in 2017"
baseurl: ""
url: "http://www.adventuresnotvacations.com"
twitter_username: randallwbrown
github_username:  blladnar
facebook_username:  StartBootstrap
instagram_username: blladnar

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
